/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as LineupsRouteImport } from './routes/lineups'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as PlayersIdRouteImport } from './routes/players.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupsRoute = LineupsRouteImport.update({
  id: '/lineups',
  path: '/lineups',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/glossary': typeof GlossaryRoute
  '/lineups': typeof LineupsRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/players/$id': typeof PlayersIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/players/': typeof PlayersIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/glossary': typeof GlossaryRoute
  '/lineups': typeof LineupsRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/players/$id': typeof PlayersIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/players': typeof PlayersIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/glossary': typeof GlossaryRoute
  '/lineups': typeof LineupsRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/players/$id': typeof PlayersIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/players/': typeof PlayersIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/glossary'
    | '/lineups'
    | '/seasons'
    | '/settings'
    | '/players/$id'
    | '/teams/$id'
    | '/players/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/glossary'
    | '/lineups'
    | '/seasons'
    | '/settings'
    | '/players/$id'
    | '/teams/$id'
    | '/players'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/glossary'
    | '/lineups'
    | '/seasons'
    | '/settings'
    | '/players/$id'
    | '/teams/$id'
    | '/players/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  GlossaryRoute: typeof GlossaryRoute
  LineupsRoute: typeof LineupsRoute
  SeasonsRoute: typeof SeasonsRoute
  SettingsRoute: typeof SettingsRoute
  PlayersIdRoute: typeof PlayersIdRoute
  TeamsIdRoute: typeof TeamsIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineups': {
      id: '/lineups'
      path: '/lineups'
      fullPath: '/lineups'
      preLoaderRoute: typeof LineupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  GlossaryRoute: GlossaryRoute,
  LineupsRoute: LineupsRoute,
  SeasonsRoute: SeasonsRoute,
  SettingsRoute: SettingsRoute,
  PlayersIdRoute: PlayersIdRoute,
  TeamsIdRoute: TeamsIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
